### PR TITLE
Updates for new CAM in NorESM2.5

### PR DESCRIPTION
**Pull request by YanchunHe**
* adapt to file tag cam.h0a
* skip diagnostics on plev and for vertical profiles
Link to discussion: https://github.com/NorESMhub/noresm3_dev_simulations/discussions/48 

Update CLM diagnostics, to:
* enable remapping SE CLM to lat/lon
* tested for climatologies and time time series. 
* test for model-obs, and model-model comparisons.

related to #1

### CODE REVIEW

**Comment by YanchunHe** [comment]
### For the new spectral element version of CAM.

Call the `diag_run` as before, and the tool should automatically detect it the SE version of CAM.

For example:
```
diag_run -m all -c casename -s 1 -e 10 -i /path/to/case
```

or
```
diag_run -m cam -c casename -s 1 -e 10 -i /path/to/case
```

Sample output:
https://ns9560k.web.sigma2.no/datalake/diagnostics/noresm/yanchun/n1850.ne30_tn14.hybrid.20240829/CAM_DIAG/

### For the new CLM diagnostics:
1. for comparing new CLM with observations (model-obs comparision)
One should use `-m ctsm` to indicate it is processing the new CLM.
```
./diag_run -m ctsm -c n1850.ne30_tn14.hybrid.20240829 -s 1 -e 14 -i /projects/NS9560K-datalake/noresm3/case
```
Sample output:
https://ns9560k.web.sigma2.no/datalake/diagnostics/noresm/yanchun/n1850.ne30_tn14.hybrid.20240829/CLM_DIAG/yrs1to14-obs/

2. For comparing two new CLM simulations (model1-model2 comparison)
```
/diag_run -m ctsm -c1 n1850.ne30_tn14.hybrid.20240829 -s1 1 -e1 14 -c2 n1850.ne30_tn14.hybrid_fatessp.202401007 -s2 1 -e2 14 -i1 /projects/NS9560K-datalake/noresm3/cases -i2 /projects /NS9560K-datalake/noresm3/cases
```

Sample output:
https://ns9560k.web.sigma2.no/datalake/diagnostics/noresm/yanchun/n1850.ne30_tn14.hybrid.20240829/CLM_DIAG/yrs1to14-n1850.ne30_tn14.hybrid_fatessp.202401007/

3. For comparing new CLM simulation with old CLM (NorESM2 version):
One has to go to the `passive mode` of `diag_run` to tweak a little bit.
```
./diag_run -m ctsm -c1 n1850.ne30_tn14.hybrid.20240829 -s1 1 -e1 14 -c2 N1850_f19_tn14_20190621 -s2 1601 -e2 1614 -i1 /projects/NS9560K-datalake/noresm3/cases -i2 /projects/NS9560K/noresm/cases -p
```
Then
```
cd /scratch/$USER/diagnostics/noresm/out/CLM_DIAG
```
and change in the `lnd_template.csh`
`setenv regrid_2   1` to `setenv regrid_2   0`

then execute the script:
```
./lnd_template.csh
```

Sample output:
https://ns9560k.web.sigma2.no/datalake/diagnostics/noresm/yanchun/n1850.ne30_tn14.hybrid.20240829/CLM_DIAG/yrs1to14-N1850_f19_tn14_20190621/

Note, for the CMIP6 version of CLM, the diagnostic only works for some simulations with the monthly averaged field stored in files of each individual months.  For those with 12-monthly files stored in one single file of a year, will not work. There is difficulty for NCO to deal with these name conventions.

**Comment by mvertens** [comment]
@YanchunHe - this is fantastic. Thank you!
I think it would be incredibly useful if this information could also be available in the discussions or the wiki. @adagj @gold2718 - where do you think this should go? 
Also - at this point are we recommending to generate CAM diagnostics with diag_run as described above or with the new ADF?

**Comment by gold2718** [comment]
I am happy to set these instructions up on the wiki.
Do we want to mention the installed location(s) of `diag_run`?

**Comment by gold2718** [comment]
I updated the wiki to include the instructions from @YanchunHe.
I also created a table of contents to make it easier to find material.

**Comment by mvertens** [comment]
@gold2718 - thanks so much!

**Comment by YanchunHe** [comment]
Great, thanks @mvertens and @gold2718 !

I merge the updates now.

**Pull request merged**
